version: '3.7'
services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: "resultDB"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "inf273"
      POSTGRES_ROOT_PASSWORD: "root"
    ports:
      - "5432:5432"